src/Entity/User.php
<?php

/*
 * This file is part of the Kelemploi application.
 *
 * (c) Bechir Ba <bechiirr71@gmail.com>
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @UniqueEntity(fields="username", message="Ce nom d'utilisateur existe déjà")
 *
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="app_user")
 * @ORM\HasLifecycleCallbacks()
 */
class User extends BaseUser implements EquatableInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Civility")
     * @ORM\JoinColumn(nullable=true)
     */
    private $civility;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, unique=false, nullable=true)
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="datetime")
     */
    private $submittedAt;

    /**
     * @var Avatar
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Avatar", orphanRemoval=true, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, unique=false)
     * @Assert\Country
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=10, nullable=true, unique=false)
     */
    private $locale;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="owners")
     */
    private $company;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Region")
     */
    private $region;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $viewCount;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $age;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Gender")
     */
    private $gender;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AccountType")
     */
    private $accountType;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nationality")
     */
    private $nationality;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Resume", inversedBy="user", cascade={"persist", "remove"})
     */
    private $resume;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Apply", mappedBy="candidate")
     */
    private $applies;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Application")
     */
    private $bookmarkedJobs;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Company")
     */
    private $bookmarkedCompanies;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="author")
     */
    private $articles;

    const NUM_ITEMS = 15;

    const EMPLOYER = 'app.employer';
    const CANDIDATE = 'app.candidate';

    public function __construct()
    {
        parent::__construct();
        $this->locale = 'fr';

        $this->viewCount = 0;
        $this->applies = new ArrayCollection();
        $this->bookmarkedJobs = new ArrayCollection();
        $this->bookmarkedCompanies = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setEmail($email)
    {
        $this->email = $email;
        if (!$this->username) {
            $this->username = $email;
        }

        return $this;
    }

    public function getCivility(): ?Civility
    {
        return $this->civility;
    }

    public function setCivility(?Civility $civility): self
    {
        $this->civility = $civility;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName(): string
    {
        return $this->firstName
            ? $this->firstName . ' ' . $this->lastName
            : $this->username;
    }

    public function getJobTitle(): string
    {
        return ($this->haveResume() && $this->resume->getTitle())
            ? $this->resume->getTitle()
            : $this->getFullName();
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale(?string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getSubmittedAt(): ?\DateTimeInterface
    {
        return $this->submittedAt;
    }

    public function getAvatar()
    {
        return $this->avatar;
    }

    public function setAvatar(?Avatar $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function haveCompany(): bool
    {
        return null !== $this->company;
    }

    /**
     * {@inheritdoc}
     */
    public function serialize(): string
    {
        return serialize([
            $this->id,
            $this->username,
            $this->phoneNumber,
            $this->email,
            $this->region,
            $this->plainPassword,
            $this->password,
            $this->submittedAt,
            $this->roles,
            $this->avatar,
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function unserialize($serialized): void
    {
        [
            $this->id,
            $this->username,
            $this->phoneNumber,
            $this->email,
            $this->region,
            $this->plainPassword,
            $this->password,
            $this->submittedAt,
            $this->roles,
            $this->avatar,
        ] = unserialize($serialized);
    }

    /**
     * @ORM\PrePersist
     */
    public function setSubmittedAt()
    {
        $this->submittedAt = new \DateTime();
    }

    public function isEqualTo(UserInterface $user)
    {
        if ($this->password !== $user->getPassword()) {
            return false;
        }
        if ($this->salt !== $user->getSalt()) {
            return false;
        }
        if ($this->username !== $user->getUsername()) {
            return false;
        }

        return true;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(?string $about): self
    {
        $this->about = $about;

        return $this;
    }

    public function getRegion(): ?Region
    {
        return $this->region;
    }

    public function setRegion(?Region $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getViewCount(): ?int
    {
        return $this->viewCount;
    }

    public function increaseViewCount(): self
    {
        ++$this->viewCount;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(?int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getGender(): ?Gender
    {
        return $this->gender;
    }

    public function setGender(?Gender $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getAccountType(): ?AccountType
    {
        return $this->accountType;
    }

    public function setAccountType(?AccountType $accountType): self
    {
        $this->accountType = $accountType;

        return $this;
    }

    public function haveResume(): bool
    {
        return null !== $this->resume && !empty($this->resume);
    }

    public function getNationality(): ?Nationality
    {
        return $this->nationality;
    }

    public function setNationality(?Nationality $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function isCandidate(): bool
    {
        return $this->accountType && self::CANDIDATE == $this->accountType->getName();
    }

    public function isEmployer(): bool
    {
        return $this->accountType && self::EMPLOYER == $this->accountType->getName();
    }

    public function getResume(): ?Resume
    {
        return $this->resume;
    }

    public function setResume(?Resume $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function updateRoles()
    {
        if ($this->isEmployer()) {
            $this->addRole('ROLE_EMPLOYER');
        } elseif ($this->isCandidate()) {
            $this->addRole('ROLE_CANDIDATE');
        }
    }

    /**
     * @return Collection|Apply[]
     */
    public function getApplies(): Collection
    {

templates/util/alerts.twig
{% macro alert(type, icon, text, domain) %}
    <div class="alert-wrap">
        <div class="jy-alert {{ type }}-alert">
            <div class="icon">
                <i class="fas {{ icon }}"></i>
            </div>
            <p>{{ text|trans({}, domain) }}</p>
        </div>
    </div>
{% endmacro %}

{% macro default(text, domain = 'messages') %}
    {{ _self.alert('default', 'fa-info-circle', text, domain) }}
{% endmacro %}

{% macro success(text, domain = 'messages') %}
    {{ _self.alert('success', 'fa-check-circle', text, domain)}}
{% endmacro %}

{% macro info(text, domain = 'messages') %}
    {{ _self.alert('info', 'fa-info-circle', text, domain)}}
{% endmacro %}

{% macro warning(text, domain = 'messages') %}
    {{ _self.alert('warning', 'fa-warning', text, domain)}}
{% endmacro %}

{% macro danger(text, domain = 'messages') %}
    {{ _self.alert('danger', 'fa-exclamation-circle', text, domain)}}
{% endmacro %}

templates/util/breadcrumb.html.twig
{% macro level_1(title) %}
    <!-- Breadcrumb -->
    <div class="alice-bg py-5 reveal-1">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumb-area">
                        <h1>{{ title|trans }}</h1>
                        <nav aria-label="breadcrumb">
                            <ol itemscope itemtype="http://schema.org/BreadcrumbList" class="breadcrumb">
                                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" class="breadcrumb-item">
                                    <a itemprop="item" href="{{ path('index') }}">
                                    <span itemprop="name">{{ 'layout.home'|trans }}</span>
                                    </a>
                                    <meta itemprop="position" content="1" />
                                </li>
                                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" aria-current="page" class="breadcrumb-item active">
                                    <a itemprop="item" href="javascript:void()">
                                        <span itemprop="name">{{ title|trans }}</span>
                                        <meta itemprop="position" content="2" />
                                    </a>
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->
{% endmacro %}


{% macro level_2(l1, title) %}
    <!-- Breadcrumb -->
    <div class="alice-bg py-5 reveal-1">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="breadcrumb-area">
                        <h1>{{ title }}</h1>
                        <nav aria-label="breadcrumb">
                            <ol itemscope itemtype="http://schema.org/BreadcrumbList" class="breadcrumb">
                                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" class="breadcrumb-item">
                                    <a itemprop="item" href="{{ path('index') }}" href="{{ path('index') }}">
                                    <span itemprop="name">Accueil</span>
                                    </a>
                                    <meta itemprop="position" content="1" />
                                </li>
                                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" class="breadcrumb-item">
                                    <a itemprop="item" href="{{ path(l1.path) }}" href="{{ path(l1.path) }}">
                                    <span itemprop="name">{{ l1.title }}</span>
                                    </a>
                                    <meta itemprop="position" content="2" />
                                </li>
                                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" aria-current="page" class="breadcrumb-item active">
                                    <span itemprop="item">
                                        <span itemprop="name">{{ title }}</span>
                                        <meta itemprop="position" content="3" />
                                    </span>
                                </li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Breadcrumb End -->
{% endmacro %}

templates/util/candidate_widgets.twig
{% macro thumb(user, path = '#') %}
    <div class="thumb">
        <a href="{{ path }}">
            {% if user.avatar %}
                <img class="img-fluid" src="{{ vich_uploader_asset(user.avatar, 'avatarFile') }}"/>
            {% else %}
                <img src="{{ asset('images/account/default-avatar-profile.jpg') }}" class="img-fluid" alt="No image">
            {% endif %}
        </a>
    </div>
{% endmacro %}

{% macro infos(user) %}
    <div class="info">
        {% if user.resume and user.resume.jobCategory %}
            <span class="work-post">
                <a href="#" onclick="return false">
                    <i data-feather="check-square"></i>{{ user.resume.jobCategory|trans({}, 'jobs-categories') }}</a>
            </span>
        {% endif %}
        
        {% if user.region %}
            <span class="location">
                <a href="#" onclick="return false">
                    <i data-feather="map-pin"></i>{{ user.region|trans({}, 'regions')}}</a>
            </span>
        {% endif %}
    </div>
{% endmacro %}

templates/util/company_widgets.twig
{% macro thumb(company, path = '#') %}
    <div class="thumb">
        <a href="{{ path }}">
            {% if company and company.photo %}
                <img alt="{{ company.name }} Logo" class="img-fluid" src="{{ vich_uploader_asset(company.photo, 'companyPhotoFile') }}"/>
            {% else %}
                <img alt="{{ company ? company.name : '' }} Logo" class="img-fluid" src="{{ asset('images/account/default-logo.png') }}"/>
            {% endif %}
        </a>
    </div>
{% endmacro %}

{% macro infos(company, class = 'location', category = null) %}
    <div class="info">
        {% if company.industry %}
            <span class="company-category">
                <a href="#">
                    <i data-feather="briefcase"></i>
                    {% if category %}
                        {{ category|trans({}, 'jobs-categories') }}
                    {% else %}
                        {{ company.industry }}
                    {% endif %}
                </a>
            </span>
        {% endif %}
        <span class="{{ class }}">
            <a href="#">
                <i data-feather="map-pin"></i>
                {% if company.region %}
                    {{ company.region|trans({}, 'regions') }}
                {% else %}
                    {{ 'app.sn'|trans }}
                {% endif %}
            </a>
        </span>
    </div>
{% endmacro %}

{% macro office_location(name) %}
    <span itemprop="jobLocation" itemscope itemtype="http://schema.org/Place" class="office-location">
        <a href="#">
            <i data-feather="map-pin"></i>
            <span itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
                <span itemprop="addressLocality">{{ name|trans({}, 'regions') }}</span>
            </span>
        </a>
    </span>
{% endmacro %}

{% macro job_type(contract) %}
    {% set class = contract|lower %}

    {% if class == 'cdd' or class == 'stage' %}
        {% set class = 'temporary' %}
    {% elseif class == 'cdi' %}
        {% set class = 'full-time' %}
    {% elseif class == 'alternance' %}
        {% set class = 'part-time' %}
    {% endif %}

    <span class="job-type {{ class }}">
        <a href="{{ path('applications_list', {contract: contract|trans|lower }) }}">
            <i data-feather="clock"></i><span itemprop="employmentType">{{ contract|trans() }}</span></a>
    </span>
{% endmacro %}

templates/util/schema.twig
{% macro company_info_json(company) %}
    <script type="application/ld+json">
    {
        "@context" : "http://schema.org",
        "@type" : "Organization",
        "name": "{{ company.name }}",
        {% if company.description %}
        "description": "{{ company.description }}",
        {% endif %}
        {% if company.photo %}
            "image": "{{ app.request.getSchemeAndHttpHost ~ vich_uploader_asset(company.photo, 'companyPhotoFile') }}",
        {% endif %}
        "location": "{{ company.region|trans({}, 'regions') }} {{ company.address }}",
        "url" : "{{ app.request.getSchemeAndHttpHost ~ path('company_show', {slug: company.slug}) }}",
        "contactPoint" : [
            { "@type" : "ContactPoint",
                {% if company.email %}
                "email": "{{ company.email }}"{% endif %}{% if company.website %},
                "url": "{{ company.website }}"
                {% endif %}
            }
        ]
    }
    </script>
{% endmacro %}

{% macro job_post_details_json(job) %}
    <script type="application/ld+json">
    {
        "@context": "http://schema.org/",
        {% if job.company.photo %}
            "image": "{{ app.request.getSchemeAndHttpHost ~ vich_uploader_asset(job.company.photo, 'companyPhotoFile') }}",
        {% endif %}
        "@type": "JobPosting",
        "title": "{{ job.jobTitle }}",
        "url": "{{ app.request.getSchemeAndHttpHost ~ path('application_show', {slug: job.slug}) }}",
        "employmentType": "{{ job.contractType|trans }}",
        "datePosted": "{{ job.dates.start|date('Y-m-d') }}",
        "description": "{{ job.description|striptags }}",
        "relevantOccupation": {
            "@type": "Occupation",
            "name": "{{ job.jobTitle }}",
            "occupationalCategory": "{{ job.postCategory|trans({}, 'jobs-categories') }}",
        },
        "hiringOrganization": {
            "@type": "Organization",
            "name": "{{ job.company.name }}"
        },
        "educationRequirements": "{{ job.minStudyLevel|trans }}",
        "experienceRequirements": "{{ job.experience|trans }}",
        "industry": "{{ job.company.industry }}",
        "jobLocation": {
            "@type": "Place",
            "address": {
                "@type": "PostalAddress",
                "addressLocality": "{{ job.company.region|trans({}, 'regions') }}"
            }
        },
        "qualifications": "",
        "responsibilities": "{{ job.responsibilities|striptags }}",
        "jobBenefits": "{{ job.benefits|striptags }}"
    }
    </script>
{% endmacro %}

templates/util/util.twig
{% macro formRequired() %}
    <span class="text-danger">*</span>
{% endmacro %}

{% macro acceptTermsConditions() %}
    {{ 'text.accept_terms'|trans({'%terms_url%': path('terms_conditions'), '%privacy_url%': path('privacy')})|raw }}
{% endmacro %}

{% macro temporary_unavailable_alert() %}
    <div class="alert-wrap">
        <div class="jy-alert default-alert">
            <div class="icon">
                <i class="fas fa-info-circle"></i>
            </div>
            <p>{{ 'text.temporary_unavailable_alert'|trans }}</p>
        </div>
    </div>
{% endmacro %}