src/Entity/User.php
<?php

/*
 * This file is part of the Kelemploi application.
 *
 * (c) Bechir Ba <bechiirr71@gmail.com>
 */

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use FOS\UserBundle\Model\User as BaseUser;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\EquatableInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @UniqueEntity(fields="username", message="Ce nom d'utilisateur existe déjà")
 *
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="app_user")
 * @ORM\HasLifecycleCallbacks()
 */
class User extends BaseUser implements EquatableInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Civility")
     * @ORM\JoinColumn(nullable=true)
     */
    private $civility;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255, unique=false, nullable=true)
     */
    private $phoneNumber;

    /**
     * @ORM\Column(type="datetime")
     */
    private $submittedAt;

    /**
     * @var Avatar
     *
     * @ORM\OneToOne(targetEntity="App\Entity\Avatar", orphanRemoval=true, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $avatar;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, unique=false)
     * @Assert\Country
     */
    private $country;

    /**
     * @ORM\Column(type="string", length=10, nullable=true, unique=false)
     */
    private $locale;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Company", inversedBy="owners")
     */
    private $company;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Region")
     */
    private $region;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $viewCount;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $age;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Gender")
     */
    private $gender;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\AccountType")
     */
    private $accountType;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Nationality")
     */
    private $nationality;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Resume", inversedBy="user", cascade={"persist", "remove"})
     */
    private $resume;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Apply", mappedBy="candidate")
     */
    private $applies;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Application")
     */
    private $bookmarkedJobs;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Company")
     */
    private $bookmarkedCompanies;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="author")
     */
    private $articles;

    const NUM_ITEMS = 15;

    const EMPLOYER = 'app.employer';
    const CANDIDATE = 'app.candidate';

    public function __construct()
    {
        parent::__construct();
        $this->locale = 'fr';

        $this->viewCount = 0;
        $this->applies = new ArrayCollection();
        $this->bookmarkedJobs = new ArrayCollection();
        $this->bookmarkedCompanies = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setEmail($email)
    {
        $this->email = $email;
        if (!$this->username) {
            $this->username = $email;
        }

        return $this;
    }

    public function getCivility(): ?Civility
    {
        return $this->civility;
    }

    public function setCivility(?Civility $civility): self
    {
        $this->civility = $civility;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getFullName(): string
    {
        return $this->firstName
            ? $this->firstName . ' ' . $this->lastName
            : $this->username;
    }

    public function getJobTitle(): string
    {
        return ($this->haveResume() && $this->resume->getTitle())
            ? $this->resume->getTitle()
            : $this->getFullName();
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(string $phoneNumber): self
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(?string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getLocale()
    {
        return $this->locale;
    }

    public function setLocale(?string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getSubmittedAt(): ?\DateTimeInterface
    {
        return $this->submittedAt;
    }

    public function getAvatar()
    {
        return $this->avatar;
    }

    public function setAvatar(?Avatar $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): self
    {
        $this->company = $company;

        return $this;
    }

    public function haveCompany(): bool
    {
        return null !== $this->company;
    }

    /**
     * {@inheritdoc}
     */
    public function serialize(): string
    {
        return serialize([
            $this->id,
            $this->username,
            $this->phoneNumber,
            $this->email,
            $this->region,
            $this->plainPassword,
            $this->password,
            $this->submittedAt,
            $this->roles,
            $this->avatar,
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function unserialize($serialized): void
    {
        [
            $this->id,
            $this->username,
            $this->phoneNumber,
            $this->email,
            $this->region,
            $this->plainPassword,
            $this->password,
            $this->submittedAt,
            $this->roles,
            $this->avatar,
        ] = unserialize($serialized);
    }

    /**
     * @ORM\PrePersist
     */
    public function setSubmittedAt()
    {
        $this->submittedAt = new \DateTime();
    }

    public function isEqualTo(UserInterface $user)
    {
        if ($this->password !== $user->getPassword()) {
            return false;
        }
        if ($this->salt !== $user->getSalt()) {
            return false;
        }
        if ($this->username !== $user->getUsername()) {
            return false;
        }

        return true;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(?string $about): self
    {
        $this->about = $about;

        return $this;
    }

    public function getRegion(): ?Region
    {
        return $this->region;
    }

    public function setRegion(?Region $region): self
    {
        $this->region = $region;

        return $this;
    }

    public function getViewCount(): ?int
    {
        return $this->viewCount;
    }

    public function increaseViewCount(): self
    {
        ++$this->viewCount;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(?int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getGender(): ?Gender
    {
        return $this->gender;
    }

    public function setGender(?Gender $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getAccountType(): ?AccountType
    {
        return $this->accountType;
    }

    public function setAccountType(?AccountType $accountType): self
    {
        $this->accountType = $accountType;

        return $this;
    }

    public function haveResume(): bool
    {
        return null !== $this->resume && !empty($this->resume);
    }

    public function getNationality(): ?Nationality
    {
        return $this->nationality;
    }

    public function setNationality(?Nationality $nationality): self
    {
        $this->nationality = $nationality;

        return $this;
    }

    public function isCandidate(): bool
    {
        return $this->accountType && self::CANDIDATE == $this->accountType->getName();
    }

    public function isEmployer(): bool
    {
        return $this->accountType && self::EMPLOYER == $this->accountType->getName();
    }

    public function getResume(): ?Resume
    {
        return $this->resume;
    }

    public function setResume(?Resume $resume): self
    {
        $this->resume = $resume;

        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function updateRoles()
    {
        if ($this->isEmployer()) {
            $this->addRole('ROLE_EMPLOYER');
        } elseif ($this->isCandidate()) {
            $this->addRole('ROLE_CANDIDATE');
        }
    }

    /**
     * @return Collection|Apply[]
     */
    public function getApplies(): Collection
    {

src/Form/UserType.php
<?php

/*
 * This file is part of the Kelemploi application.
 *
 * (c) Bechir Ba <bechiirr71@gmail.com>
 */

namespace App\Form;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    private $em;
    private $session;

    public function __construct(EntityManagerInterface $em, SessionInterface $session)
    {
        $this->em = $em;
        $this->session = $session;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('username', TextType::class)
            //->add('phoneNumber', TextType::class)
            //->add('accountType', AccountType::class)
            ->add('email', EmailType::class)
            ->add('password', RepeatedType::class, [
                'type' => PasswordType::class,
                'required' => false,
                'invalid_message' => 'form.invalid_password_message',
                'first_options' => ['attr' => ['placeholder' => 'form.password', 'class' => 'form-control']],
                'second_options' => ['attr' => ['placeholder' => 'form.confirm_password', 'class' => 'form-control']],
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/base.html.twig
{% extends 'base.html.twig' %}

{% import 'util/breadcrumb.html.twig' as breadcrumb %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('assets/css/html5-simple-date-input-polyfill.css') }}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('dashboard/css/dashboard.css') }}">
{% endblock %}

{% block main %}

    {{ breadcrumb.level_1('employer.breadcrumb') }}

    <div class="alice-bg section-padding-bottom">
        <div class="container no-gliters">
            <div class="row no-gliters">
                <div class="col">
                    <div class="dashboard-container">
                        <div class="dashboard-content-wrapper {% block wrapper_class %}{% endblock %}">
                            {% block content %}
                            {% endblock %}
                        </div>
                        {% include 'user/dashboard-sidebar.html.twig' with {active: active, user: user} %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script src="{{ asset('assets/js/html5-simple-date-input-polyfill.min.js') }}"></script>
    <script src="{{ asset('dashboard/js/dashboard.js') }}"></script>
    <script src="{{ asset('dashboard/js/datePicker.js') }}"></script>
    <script src="{{ asset('dashboard/js/upload-input.js') }}"></script>
{% endblock %}

templates/user/change-password.html.twig
{% extends 'user/base.html.twig' %}

{% trans_default_domin 'user' %}

{% block title %}
    {{ 'change_password.title'|trans }}
{% endblock %}

{% block content %}

    <div class="dashboard-section basic-info-input">
        <h4>
            <i data-feather="lock"></i>Change Password</h4>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Current Password</label>
            <div class="col-sm-9">
                <input class="form-control" placeholder="Current Password" type="password">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">New Password</label>
            <div class="col-sm-9">
                <input class="form-control" placeholder="New Password" type="password">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label">Retype Password</label>
            <div class="col-sm-9">
                <input class="form-control" placeholder="Retype Password" type="password">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <button class="button">Save Change</button>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/dashboard-sidebar.html.twig
{% trans_default_domain 'user' %}

<div class="dashboard-sidebar">
    <div class="user-info mb-0 border-bottom">
        <div class="thumb">
            {% if app.user.avatar %}
                <img alt="{{ app.user.fullName }} Photo" class="img-fluid" src="{{ vich_uploader_asset(app.user.avatar, 'avatarFile') }}">
            {% else %}
                <img alt="No image" class="img-fluid" src="{{ asset('images/account/default-avatar-profile.jpg') }}">
            {% endif %}
        </div>
        <div class="user-body">
            <h5>Mr. {{ user.lastname }}</h5>
            <span>{{ user.username }}</span>
        </div>
    </div>
    {# <div class="profile-progress">
        <div class="progress-item">
            <div class="progress-head">
                <p class="progress-on">{{ 'word.profile'|trans({}, 'messages') }}</p>
            </div>
            <div class="progress-body">
                <div class="progress">
                    <div aria-valuemax="100" aria-valuemin="0" aria-valuenow="70" class="progress-bar" role="progressbar" style="width: 0;"></div>
                </div>
                <p class="progress-to">70%</p>
            </div>
        </div>
    </div> #}
    <div class="dashboard-menu pt-3">
        <ul>
            <li {% if active == 'dashboard' %}class="active"{% endif %}>
                <i class="fas fa-home"></i>
                <a href="{{ path('user_dashboard') }}">{{ 'employer.dashboard'|trans({}, 'messages') }}</a>
            </li>
            <li {% if active == 'edit-profile' %}class="active"{% endif %}>
                <i class="fas fa-user"></i><a href="{{ path('user_profile_edit') }}">{{ 'edit_profile'|trans }}</a>
            </li>
            <li {% if active == 'resume' %}class="active"{% endif %}>
                <i class="fas fa-file-alt"></i><a href="{{ path('resume') }}">{{ 'resume'|trans }}</a>
            </li>
            <li {% if active == 'edit-resume' %}class="active"{% endif %}>
                <i class="fas fa-edit"></i><a href="{{ path('edit_resume') }}">{{ 'edit_resume'|trans }}</a>
            </li>
            <li {% if active == 'bookmarked' %}class="active"{% endif %}>
                <i class="fas fa-heart"></i><a href="{{ path('user_bookmarked') }}">{{ 'bookmarked'|trans }}</a>
            </li>
            <li {% if active == 'applied-jobs' %}class="active"{% endif %}>
                <i class="fas fa-check-square"></i><a href="{{ path('user_applied') }}">{{ 'applied_jobs'|trans }}</a>
            </li>
            {# <li {% if active == 'messages' %}class="active"{% endif %}>
                <i class="fas fa-comment"></i><a href="{{ path('user_messages') }}">{{ 'messages'|trans }}</a>
            </li> #}
        </ul>
        <ul class="delete">
            <li>
                <i class="fas fa-power-off"></i>
                <a href="{{ path('fos_user_security_logout') }}">{{ 'user.logout'|trans({}, 'messages') }}</a>
            </li>
        </ul>

        {# Delete account modal #}
        {% include 'common/delete-account-modal.html.twig' %}
    </div>
</div>

templates/user/edit-profile.html.twig
{% extends 'user/base.html.twig' %}

{% trans_default_domain 'user' %}

{% block title %}{{ 'edit_profile'|trans }}{% endblock %}
{% block content %}
    {{ form_start(form, {'attr': { 'class': 'dashboard-form job-post-form' } }) }}
        <div class="dashboard-section upload-profile-photo">
            <div class="update-photo">
                {% if app.user.avatar %}
                    <img alt="{{ app.user.fullName }} Photo" class="image" src="{{ vich_uploader_asset(app.user.avatar, 'avatarFile') }}">
                {% else %}
                    <img alt="No image" class="image" src="{{ asset('images/account/default-avatar-profile.jpg') }}">
                {% endif %}
                
            </div>
            <div class="file-upload">{{ 'form.edit_avatar'|trans }}
                {{ form_widget(form.avatar.avatarFile, {'attr': {'class': 'file-input'}}) }}
            </div>
        </div>
        <div class="dashboard-section basic-info-input">
            <h4><i data-feather="user-check"></i>{{ 'form.edit_infos'|trans }}</h4>
            {% if not form.vars.valid %}
                <div class="form-group row">
                    {% for children in form.children %}
                        {% if not children.vars.valid %}
                            <div class="alert alert-danger">
                                {% if children.first is defined %}
                                    {{ form_errors(children.first) }}
                                {% else %}
                                    {{ form_errors(children) }}
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            {% endif %}
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'form.first_name'|trans }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.firstName, {'attr': {'class': 'form-control'}})}}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'form.last_name'|trans }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.lastName, {'attr': {'class': 'form-control'}})}}
                </div>
            </div>
            {# <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'form.username'|trans }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.username, {'attr': {'class': 'form-control'}})}}
                </div>
            </div> #}
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'form.civility'|trans }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.civility, {'attr': {'class': 'form-control'}})}}
                    <i class="fa fa-caret-down"></i>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'form.email'|trans }}</label>
                <div class="col-sm-9">
                    <p class="text-muted">{{ app.user.email }}</p>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'form.phone'|trans }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.phoneNumber, {'attr': {'class': 'form-control'}})}}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'form.region'|trans }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.region, {'attr': {'class': 'form-control'}})}}
                    <i class="fa fa-caret-down"></i>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'candidate.domain'|trans({}, 'messages') }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.jobCategory, {'attr': {'class': 'form-control'}})}}
                    <i class="fa fa-caret-down"></i>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'form.expertise.label'|trans }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.experience, {'attr': {'class': 'form-control'}})}}
                    <i class="fa fa-caret-down"></i>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'job.level'|trans({}, 'messages') }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.studyLevel, {'attr': {'class': 'form-control'}})}}
                    <i class="fa fa-caret-down"></i>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'job.age'|trans({}, 'messages') }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.age, {'attr': {'class': 'form-control'}})}}
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'job.gender'|trans({}, 'messages') }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.gender, {'attr': {'class': 'form-control'}})}}
                    <i class="fa fa-caret-down"></i>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-3 col-form-label">{{ 'form.about_user.label'|trans }}</label>
                <div class="col-sm-9">
                    {{ form_widget(form.about, {'attr': {'class': 'form-control'}}) }}
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <button type="submit" class="button">{{ 'form.save_change'|trans }}</button>
            </div>
        </div>
    {{ form_end(form) }}
{% endblock %}

templates/user/settings.html.twig
{% extends 'user/base.html.twig' %}

{% import 'util/util.twig' as util %}

{% block content %}
    {{ util.temporary_unavailable_alert() }}
{% endblock %}